sudo: required
services:
    - docker 


before_install:
    - docker build -t izhonline/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true izhonline/docker-react npm run test -- --coverage